spring.application.name=agent-service
server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5004/agent_db
spring.datasource.username=siem_user
spring.datasource.password=siem_password
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=agent-service
account.service.url=http://localhost:8081
jwt.secret.key=${JWT_SECRET_KEY}
