INSERT INTO global_rule_templates (id, name, description, severity, field_to_watch, expected_value, threshold, window_minutes) VALUES (1, 'Brute Force Attack Detected', 'Multiple failed login attempts.', 'HIGH', 'event.outcome', 'failure', 5, 10) ON CONFLICT (id) DO NOTHING;
INSERT INTO template_remediation_steps (template_id, step) SELECT 1, 'Go to {{room}} immediately and find machine {{host}}.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 1 AND step = 'Go to {{room}} immediately and find machine {{host}}.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 1, 'Physically disconnect the network cable from the back of the computer.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 1 AND step = 'Physically disconnect the network cable from the back of the computer.');

INSERT INTO global_rule_templates (id, name, description, severity, field_to_watch, expected_value, threshold, window_minutes) VALUES (2, 'Potential Ransomware Detected', 'Massive file modification or system file access detected.', 'HIGH', 'event.category', 'file_tampering', 10, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO template_remediation_steps (template_id, step) SELECT 2, 'Unplug the power cable from machine {{host}} in {{room}}.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 2 AND step = 'Unplug the power cable from machine {{host}} in {{room}}.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 2, 'DO NOT restart the computer.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 2 AND step = 'DO NOT restart the computer.');

INSERT INTO global_rule_templates (id, name, description, severity, field_to_watch, expected_value, threshold, window_minutes) VALUES (3, 'Unauthorized User Creation', 'A new user account was created locally on a machine.', 'MEDIUM', 'event.action', 'user_created', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO template_remediation_steps (template_id, step) SELECT 3, 'Check machine {{host}} in {{room}} for unauthorized account creation.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 3 AND step = 'Check machine {{host}} in {{room}} for unauthorized account creation.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 3, 'Verify whether this was a planned change.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 3 AND step = 'Verify whether this was a planned change.');

INSERT INTO global_rule_templates (id, name, description, severity, field_to_watch, expected_value, threshold, window_minutes) VALUES (4, 'USB Device Inserted', 'A removable USB device was connected to a machine.', 'MEDIUM', 'event.action', 'removable_media_inserted', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO template_remediation_steps (template_id, step) SELECT 4, 'Locate machine {{host}} in {{room}}.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 4 AND step = 'Locate machine {{host}} in {{room}}.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 4, 'Ask the user to remove the USB device immediately.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 4 AND step = 'Ask the user to remove the USB device immediately.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 4, 'Inspect the device and verify no unauthorised files were transferred.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 4 AND step = 'Inspect the device and verify no unauthorised files were transferred.');

INSERT INTO global_rule_templates (id, name, description, severity, field_to_watch, expected_value, threshold, window_minutes) VALUES (5, 'Mass File Deletion Detected', 'A large number of files were deleted in a short period, which may indicate ransomware or a malicious wipe.', 'HIGH', 'event.action', 'file_deleted', 20, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO template_remediation_steps (template_id, step) SELECT 5, 'Do NOT touch machine {{host}} in {{room}}.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 5 AND step = 'Do NOT touch machine {{host}} in {{room}}.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 5, 'Disconnect the network cable from the back of the computer immediately.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 5 AND step = 'Disconnect the network cable from the back of the computer immediately.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 5, 'Do not restart or shut down the machine.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 5 AND step = 'Do not restart or shut down the machine.');

INSERT INTO global_rule_templates (id, name, description, severity, field_to_watch, expected_value, threshold, window_minutes) VALUES (6, 'Scheduled Task Created', 'A new scheduled task or startup program was registered on a machine, which is a common way for malware to persist.', 'MEDIUM', 'event.action', 'scheduled_task_created', 1, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO template_remediation_steps (template_id, step) SELECT 6, 'Check machine {{host}} in {{room}} — do not restart it.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 6 AND step = 'Check machine {{host}} in {{room}} — do not restart it.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 6, 'Verify whether any software was recently installed on this machine.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 6 AND step = 'Verify whether any software was recently installed on this machine.');
INSERT INTO template_remediation_steps (template_id, step) SELECT 6, 'If no planned change was made, isolate the machine by unplugging the network cable.' WHERE NOT EXISTS (SELECT 1 FROM template_remediation_steps WHERE template_id = 6 AND step = 'If no planned change was made, isolate the machine by unplugging the network cable.');

ALTER TABLE global_rule_templates ALTER COLUMN id RESTART WITH 7;
