spring.application.name=aggregation-service
server.port=8089
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

account.service.url=http://localhost:8081
agent.service.url=http://localhost:8086
spring.cache.type=caffeine
spring.cache.cache-names=apiKeys
spring.cache.caffeine.spec=maximumSize=10000,expireAfterWrite=15m
